# Site Info
title:             'ngenty'
tagline:           'Work of Nicolas Genty, former web-designer and future front-end developer.'
description:       'This portfolio uses <a href="#" target="_self">Jekyll</a>.<br>Made with <span id="footer_emoji">emojis</span> by <a href="https://ngenty.com" target="_self">@ngenty</a>.'
baseurl:           '' # the subpath of your site, e.g. /blog OR set this value to "" if you want your site to be root
url:               'https://ngenty.com' # the base hostname & protocol for your site, e.g. http://example.com
logo:              '/assets/public/logo.png'

# Translations # todo
# t:
#   en:
#     home:        'Home'
#     categories:  'Categories'
#     featured_posts: 'Featured Posts'
#   fr:
#     home:        'Accueil'
#     categories:  'Rubrique'
#     featured_posts: 'Articles'

# Site configurations
# languages:       [en, fr] # todo
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown:          kramdown
excerpt_separator: '<!-- more -->'
show_drafts:       false
include:           ['_pages']
sass:
  style:           full
  sass_dir:        _sass
permalink:         pretty
keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'
# Tiers
google_analytics:  UA-XXXXX-X

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Ptojects:
    - '/projects/'
  About:
    - '/about/'
  Github Project:
    - 'http://ngenty.github.io/'

# About/contact
author:
  name:            Nicolas Genty
  job_title:       future <strong>full stack designer</strong>
  description:     A passionate former <strong>web-designer</strong>, learning to become a front-end developer!
  gravatar:        34df580ff9ae66739e40205db630d632 # md5 hash of my gravatar account ID /requestHash "ngenty" (https://secure.gravatar.com/avatar/{hash})
  mail:            nicolas.genty+ngenty@gmail.com # todo: md5 hash of your email address
  social:          #todo redo (no purpose)
    - name:        linkedin
      login:       ngenty
      url:         https://www.linkedin.com/in/ngenty/
    - name:        twitter
      login:       ngenty
      url:         https://twitter.com/ngenty
    - name:        github
      login:       ngenty
      url:         https://github.com/ngenty
    - name:        codepen
      login:       ngenty
      url:         https://codepen.io/ngenty/
    - name:        dribbble
      login:       ngenty
      url:         https://dribbble.com/ngenty
    # - name:      facebook
    #   login:     <nope, never had & never will…>
    #   url:       https://dribbble.com/ngenty

# NOTE
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
